Add smoketest

diff --git a/Projects/lab4b/Makefile b/Projects/lab4b/Makefile
--- a/Projects/lab4b/Makefile
+++ b/Projects/lab4b/Makefile
@@ -15,7 +15,29 @@ dist:
 	@tar -czvf $(ARCHIVE) $(SOURCES)
 
 check:
-	
+	{
+		echo "START"
+		echo "PERIOD=5"
+		echo "SCALE=F"
+		echo "STOP"
+		echo "OFF"
+	} | ./lab4b --log=log.txt --period=2 --scale=C
+
+	if [ $? -ne 0 ]
+	then
+		echo "ERROR program has invalid exit code"
+	else
+		echo "OK passed smoketest"
+	fi
+
+	for command in START STOP PERIOD=5 SCALE=F OFF ; do \
+		grep "$command" log.txt > /dev/null
+		if [ $? -eq 0 ]
+			echo "OK passed logging test"
+		else
+			echo "ERROR failed logging test"
+		fi
+	done
 
 clean:
-	@rm -f lab4b
+	@rm -f lab4b log.txt $(ARCHIVE)
