Fix Makefile bug to avoid crashing on error

diff --git a/Projects/project-0/Makefile b/Projects/project-0/Makefile
--- a/Projects/project-0/Makefile
+++ b/Projects/project-0/Makefile
@@ -11,12 +11,16 @@ sources = lab0.c input.txt backtrace.png breakpoint.png Makefile README
 build:
 	@$(CC) $(CFLAGS) -o lab0 lab0.c
 
+
+#$? refers to the most recent exit code
+#2> redirects everything from STDERR (file descriptor 2) into a file
+#Adding a ; \ after the call allows the Makefile to not crash at the error
 check:
 	@echo "Test input" > input.txt;
 
-	@./lab0 < input.txt > output.txt
-	@diff input.txt output.txt
-	@if [ $$? -ne 0 ] ; \
+	@./lab0 < input.txt > output.txt 2> dump.txt ; \
+	diff input.txt output.txt
+	@if [ $$? -eq 0 ] ; \
 	then \
 		echo "SUCCESS: read/write"; \
 	else \
@@ -24,8 +28,8 @@ check:
 	fi
 	@rm -f output.txt
 
-	@./lab0 --input=input.txt > output.txt
-	@diff input.txt output.txt
+	@./lab0 --input=input.txt > output.txt 2> dump.txt ; \
+	diff input.txt output.txt
 	@if [ $$? -eq 0 ] ; \
 	then \
 		echo "SUCCESS: Input redirection"; \
@@ -34,8 +38,8 @@ check:
 	fi
 	@rm -f output.txt
 
-	@./lab0 --output=output.txt < input.txt
-	@diff input.txt output.txt
+	@./lab0 --output=output.txt < input.txt 2> dump.txt ; \
+	diff input.txt output.txt
 	@if [ $$? -eq 0 ] ; \
 	then \
 		echo "SUCCESS: Output redirection"; \
@@ -44,8 +48,8 @@ check:
 	fi
 	@rm -f output.txt
 
-	@./lab0 --input=input.txt --output=output.txt
-	@diff input.txt output.txt
+	@./lab0 --input=input.txt --output=output.txt 2> dump.txt ; \
+	diff input.txt output.txt
 	@if [ $$? -eq 0 ] ; \
 	then \
 		echo "SUCCESS: Input+Output redirection"; \
@@ -54,32 +58,32 @@ check:
 	fi
 	@rm -f output.txt
 
-	@./lab0 --segfault
-	@if [ $$? -eq 139 ] ; \
+	@./lab0 --segfault 2> dump.txt ; \
+	if [ $$? -eq 139 ] ; \
 	then \
 		echo "SUCCESS: Segfault trigger"; \
 	else \
 		echo "FAILED : Segfault trigger"; \
 	fi
 
-	@./lab0 --segfault --catch
-	@if [ $$? -ne 4 ] ; \
+	@./lab0 --segfault --catch 2> dump.txt ; \
+	if [ $$? -eq 4 ] ; \
 	then \
 		echo "SUCCESS: Segfault catch"; \
 	else \
 		echo "FAILED : Segfault catch"; \
 	fi
 
-	@./lab0 --fakeOption
-	@if [ $$? -eq 1 ] ; \
+	@./lab0 --fakeOption 2> dump.txt ; \
+	if [ $$? -eq 1 ] ; \
 	then \
 		echo "CAUGHT  : Incorrect argument error"; \
 	else \
 		echo "UNCAUGHT: Incorrect argument error"; \
 	fi
 
-	@./lab0 --input=fakeInput.txt --output=output.txt
-	@if [ $$? -eq 2 ] ; \
+	@./lab0 --input=fakeInput.txt --output=output.txt 2> dump.txt ; \
+	if [ $$? -eq 2 ] ; \
 	then \
 		echo "CAUGHT  : Inaccessible input error"; \
 	else \
@@ -87,17 +91,18 @@ check:
 	fi
 
 	@echo "Inaccessible file" > fakeOutput.txt
-	@chod -w fakeOutput.txt
-	@./lab0 --output=fakeOutput.txt < input.txt
-	@if [ $$? -eq 3 ] ; \
+	@chmod -w fakeOutput.txt
+	@./lab0 --output=fakeOutput.txt < input.txt 2> dump.txt ; \
+	if [ $$? -eq 3 ] ; \
 	then \
 		echo "CAUGHT  : Inaccessible output error"; \
 	else \
 		echo "UNCAUGHT: Inaccessible output error"; \
 	fi
+	@rm -f fakeOutput.txt
 
 dist:
 	@tar -czf $(ARCHIVE) $(sources)
 
 clean:
-	@rm -f lab0 output.txt $(ARCHIVE)
+	@rm -f lab0 output.txt fakeOutput.txt dump.txt $(ARCHIVE)
